apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: events-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: logging
roleRef:
  kind: ClusterRole
  name: events-reader
  apiGroup: rbac.authorization.k8s.io

