apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
  labels:
    app: stress-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-pod
  template:
    metadata:
      labels:
        app: stress-pod
    spec:
      containers:
      - name: stress-container
        image: docker.io/polinux/stress-ng:latest
        env:
        - name: DELAY_STARTUP
          value: "20"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
        args:
          - "--io"
          - "2"
          - "--vm"
          - "2"
          - "--vm-bytes"
          - "2G"
          - "--timeout"
          - "5m"
        resources:
          requests:
            memory: "50Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "2000m"
      nodeSelector:
        kubernetes.io/hostname: node1.group5project.ufl-eel6871-fa23-pg0.utah.cloudlab.us

# kubectl run basic-request-pod --image=docker.io/polinux/stress-ng --restart=Never -- --io 2 --vm-bytes 2g --timeout 60s --vm 1

# apiVersion: v1
# kind: Pod
# metadata:
#   name: pod-with-liveness-check
# spec:
#   containers:
#   - image: k8spatterns/random-generator:1.0
#     name: random-generator
#     env:
#     - name: DELAY_STARTUP
#       value: "20"
#     ports:
#     - containerPort: 8080
#     livenessProbe:
#       httpGet:
#         path: /actuator/health
#         port: 8080
#       initialDelaySeconds: 30