
apiVersion: v1
kind: Pod
metadata:
  name: stress-pod-2wq8
spec:
  restartPolicy: Never
  containers:
  - image: docker.io/polinux/stress-ng:latest
    name: stress-container
    env:
    - name: DELAY_STARTUP
      value: "20"
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 30
    args: ["--io", "2", "--vm", "2", "--vm-bytes", "4G", "--timeout", "5m"]
  nodeSelector:
    kubernetes.io/hostname: node1.group5project.ufl-eel6871-fa23-pg0.utah.cloudlab.us
    